[tool.black]
line-length = 130

[tool.isort]
profile = "black"

[tool.ruff]
line-length = 130
ignore = [
    "E741"
]

[tool.mypy]
no_implicit_optional = false
no_strict_optional = true
check_untyped_defs = true

[tool.pyright]
strictParameterNoneValue = false
reportPossiblyUnboundVariable = false
